name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'antoinekm/dixt'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: "latest"

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build Core
        run: pnpm build:core

      - name: Build Plugins
        run: pnpm build:plugins

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "🔖 release version"
          title: "🔖 release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
